version: '3.8'

services:
  app:
    container_name: chatgpt
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./src:/go/src/github.com/chatgpt
    tty: true
    env_file:
      - ./src/.env
    environment:
      - TZ=Asia/Tokyo
